/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sergeych_ttcrypt_RsaKey_Error */

#ifndef _Included_net_sergeych_ttcrypt_RsaKey_Error
#define _Included_net_sergeych_ttcrypt_RsaKey_Error
#ifdef __cplusplus
extern "C" {
#endif
#undef net_sergeych_ttcrypt_RsaKey_Error_serialVersionUID
#define net_sergeych_ttcrypt_RsaKey_Error_serialVersionUID -3042686055658047285LL
#undef net_sergeych_ttcrypt_RsaKey_Error_serialVersionUID
#define net_sergeych_ttcrypt_RsaKey_Error_serialVersionUID -3387516993124229948LL
#undef net_sergeych_ttcrypt_RsaKey_Error_serialVersionUID
#define net_sergeych_ttcrypt_RsaKey_Error_serialVersionUID 1LL
#ifdef __cplusplus
}
#endif
#endif
